version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=mysql+pymysql://user:password@mariadb:3306/task_db
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
    depends_on:
      - mariadb
      - valkey

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: always
    ports:
      - "6379:6379"
    command: ["--loglevel", "debug"]

volumes:
  mariadb_data:
